spring:
  profiles:
    active: daehwan-local
    #active: hyerin-local

  mvc:
    view:
      prefix: /jsp/
      suffix: .jsp

  http:
    servlet:
      multipart:
        enabled: true

  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

  #JSP와 같이 사용할 경우 뷰 구분을 위해 컨트롤러가 뷰 이름을 반환할때 thymeleaf/ 로 시작하면 타임리프로 처리하도록 view-names 지정
  thymeleaf:
    view-names: thymeleaf/*
    prefix: classpath:/templates/
    suffix: .html

cloud:
  aws:
    credentials:
      accessKey: AKIA2J56D2I7FQLGUX6L
      secretKey: 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
    s3:
      bucket: litebook-images
    region:
      static: ap-northeast-2
    stack:
      auto: false

--- #Production
spring:
  profiles: prod

  thymeleaf:
    cache: true

--- #hyerin-local
spring:
  profiles: hyerin-local

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    generate-ddl: true
    database: mysql
    show_sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        storage_engine: innodb
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  datasource:
    url: jdbc:mysql://localhost:3306/sns_timeline?useUnicode=yes&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: timeline
    password: timeline123

  thymeleaf:
    cache: false
    check-template-location: true
    
--- #daehwan-local
spring:
  profiles: daehwan-local

  jpa:
    database: mysql
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      show_sql: true
      format_sql: true

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sns_timeline?serverTimezone=UTC&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: sns_dev
    password: 1234

  thymeleaf:
    cache: false
    check-template-location: true

logging:
  level:
    org:
      hibernate: info

